/* Generated by Cython 0.23 */

#ifndef __PYX_HAVE__dbconn
#define __PYX_HAVE__dbconn


#ifndef __PYX_HAVE_API__dbconn

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C DL_IMPORT(PyObject) *py_print(char const *);
__PYX_EXTERN_C DL_IMPORT(PyObject) *init_table(void);
__PYX_EXTERN_C DL_IMPORT(PyObject) *has_table(char const *);

#endif /* !__PYX_HAVE_API__dbconn */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initdbconn(void);
#else
PyMODINIT_FUNC PyInit_dbconn(void);
#endif

#endif /* !__PYX_HAVE__dbconn */
